export const CLEAR = 'CLEAR'; // Array | Object
export const CONCAT = 'CONCAT'; // Array
export const DECREMENT = 'DECREMENT'; // number
export const DELETE = 'DELETE'; // Object
export const INCREMENT = 'INCREMENT'; // number
export const INSERT = 'INSERT'; // Array
export const PATCH = 'PATCH'; // Object
export const REMOVE = 'REMOVE'; // Array | Object
export const SHIFT = 'SHIFT'; // Array
export const UNSHIFT = 'UNSHIFT'; // Array
export const UPDATE = 'UPDATE'; // Array | Object
